[project]
name = "seattle-transit-dot-matrix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "brotli>=1.2.0",
    "fontmake>=3.11.0",
    "fonttools>=4.60.1",
]
